labscommunity/protocol-land

src/pages/repository/components/tabs/code-tab/index.tsx, src/pages/repository/helpers/filenameHelper.ts
Adding a file preview for image file extensions
=> render image for some file extensions

src/helpers/shortenAddress.ts, src/pages/repository/components/tabs/code-tab/TableHead.tsx, src/pages/repository/components/tabs/code-tab/index.tsx
- Add filenames to header of file previews
- Shorten address as AAAA...ZZZZ and show full address on hover
=> Feat: filenames and addresses

package.json, src/pages/repository/Repository.tsx, src/pages/repository/components/ActivityGraph.tsx, src/pages/repository/components/RepoHeader.tsx, src/pages/repository/components/tabs/settings-tab/tabConfig.ts, yarn.lock
This PR adds activity graph component to the repository header component
=> feat: add activity graph

src/pages/pull/read/components/Sidebar.tsx, src/pages/pull/read/tabs/overview/OverviewTab.tsx
This PR ensures any open PR can be merged or closed by owner or contributor only. Also requesting for reviews on PR will follow the same process.
=> fix: only owners and contributors can merge or close a PR

.github/workflows/pl-sync.yml, src/pages/home/Home.tsx
This PR adds Git CLI block on the home screen and PL Sync github workflow file that can be triggered manually
=> feat: Add Git CLI block on Home screen and PL sync workflow

src/components/Navbar/UserProfileButton.tsx, src/components/Navbar/WhitelistModal.tsx, src/helpers/constants.ts, src/stores/auth/index.ts, src/stores/auth/types.ts
This PR adds a check when user connects if they're whitelisted or not and shows a modal with Discord invite accordingly.
=> feat: check if connected user is whitelisted

package.json, src/components/Navbar/UserProfileButton.tsx, src/helpers/constants.ts, src/helpers/google-analytics/index.ts, src/pages/repository/components/RepoHeader.tsx, yarn.lock
This PR uses amplitude to track events along with Google Analytics. I didn't wanted to remove GA in this PR yet. Want to make sure Amplitude free plan is reliable momentarily before we fully retire GA. So far all events are being captured in a really nice manner.
=> feat: add amplitude to track events

src/lib/git/repo.ts, src/pages/repository/components/tabs/code-tab/index.tsx, src/pages/repository/hooks/useCommit.ts, src/stores/repository-core/index.ts, src/stores/repository-core/types.ts
- Fixed issue related to switching branch when adding files in a branch.
- Fixed issue related to not fetching commits when switching branch.
=> fix: presist branch when adding files and refresh commits on branch switch

package.json, src/lib/git/branch.ts, src/pages/issue/read/components/AssigneeAdd.tsx, src/pages/issue/read/components/Sidebar.tsx, src/pages/profile/components/Sidebar.tsx, src/pages/pull/read/components/ReviewerAdd.tsx, src/pages/pull/read/components/Sidebar.tsx, src/pages/repository/components/tabs/code-tab/header/NewBranchModal.tsx, src/stores/branch/index.ts, src/stores/user/actions/index.ts, yarn.lock
This pull request addresses multiple improvements and bug fixes:
- Resolved the `fetchUserRepos` function issue so that repos user is contributor of also shows on the user profile.
- Implemented branch name cleaning using [clean-git-ref](https://github.com/TheSavior/clean-git-ref/) during new branch creation similar to what GitHub has, accompanied by toast error message.
- Before hitting Create
- After hitting Create
- Recreating an existing branch
- Shorten address lengths for reviewers and assignees address in the PR and Issue page.
- Updated the profile username error message for improved clarity.
=> fix: branch creation and misc fixes

src/pages/pull/read/index.tsx, src/pages/repository/components/tabs/pull-requests-tab/TableHeader.tsx, src/pages/repository/components/tabs/pull-requests-tab/index.tsx
This PR adds fixes and improvements for two things:
- when a pull request is created from forked repo to parent repo, we now wait till files are loaded before merging to avoid merge failure.
- We now show PR counts for open and closed PR section
=> fix: wait till pull files are loaded and show PR counts

src/pages/repository/components/tabs/issues-tab/TableHeader.tsx, src/pages/repository/components/tabs/issues-tab/index.tsx, src/pages/repository/components/tabs/pull-requests-tab/index.tsx
This PR adds fixes and improvements for the following things:
- Show issue counts for open and closed issues.
- Show message for no open/closed Issues/PRs.
=> feat: Show issue counts, empty messages

src/helpers/constants.ts, src/lib/dragondeploy/index.ts, src/lib/git/pull-request.ts, src/lib/git/repo.ts, src/lib/user.ts, src/pages/home/components/NewRepoModal.tsx, src/pages/pull/read/tabs/files/FileCompareComponent.tsx, src/pages/repository/components/tabs/code-tab/header/AddFilesModal.tsx, src/pages/repository/components/tabs/code-tab/index.tsx, src/pages/repository/components/tabs/commits-tab/index.tsx, src/pages/repository/hooks/useBranch.ts, src/pages/repository/hooks/useCommit.ts, src/pages/repository/hooks/useFetchRepository.ts, src/pages/repository/hooks/useRepository.ts, src/stores/branch/actions/index.ts, src/stores/branch/index.ts, src/stores/pull-request/actions/index.ts, src/stores/pull-request/index.ts, src/stores/repository-core/actions/git.ts, src/stores/repository-core/index.ts, warp/protocol-land/actions/evolve.ts, warp/protocol-land/contract.ts, warp/protocol-land/types/index.ts
This PR updates UI to use id for dir instead of name
=> feat: update repositories to use id for dir instead of name

src/components/DragonDeploy/DragonDeploy.tsx, src/helpers/prices.ts, src/lib/dragondeploy/index.ts
This fixes the following issues:
- Restore branch when the dragon deploy button is unmounted.
- Add redstone fallback api for Arweave USD price.
=> fix: Dragon deploy branch and arweave price issues

scripts/deploy.js, src/helpers/constants.ts, src/lib/git/pull-request.ts, src/pages/issue/read/tabs/overview/OverviewTab.tsx, src/pages/pull/create/components/RepoDropdown.tsx, src/pages/pull/read/components/ActionButton.tsx, src/pages/pull/read/components/PullRequestHeader.tsx, src/pages/pull/read/components/ReviewerAdd.tsx, src/pages/pull/read/components/Sidebar.tsx, src/pages/pull/read/tabs/overview/OverviewTab.tsx, src/pages/repository/components/tabs/pull-requests-tab/PullRequestRow.tsx, src/pages/repository/components/tabs/pull-requests-tab/index.tsx, src/stores/pull-request/index.ts, src/stores/pull-request/types.ts, src/types/repository.ts, warp/protocol-land/actions/pull-requests.ts, warp/protocol-land/contract.ts, warp/protocol-land/types/index.ts, warp/protocol-land/utils/isInvalidInput.ts
This PR adds feature of activities in Pull Request to show different activities (reopen, closed, merged, comment, review request, approvals) and also the merged timestamp.
=> feat: PR Activity

src/pages/home/Home.tsx, src/pages/home/components/Sidebar.tsx, src/pages/issue/read/index.tsx, src/pages/profile/Profile.tsx, src/pages/profile/components/tabs/overview/components/Contributions.tsx, src/pages/pull/read/index.tsx, src/pages/repository/Repository.tsx
This PR adds paddings and necessary breakpoints to adjust layout for lower viewports
test case:
Set the viewport of your tab to 1280x685
=> refactor: add padding to adjust layouts

docs/README.md
- Add a docs folder
- Add a root README file
=> Add docs folder and README

scripts/deploy.js, src/helpers/constants.ts, src/pages/issue/read/tabs/overview/OverviewTab.tsx, src/stores/issues/actions/index.ts, src/stores/issues/index.ts, src/types/repository.ts, warp/protocol-land/actions/issues.ts, warp/protocol-land/types/index.ts
This PR adds issue activity for assigning the issue to the contributors.
=> feat: Add issue assign activity

src/components/Landing/BackedByArweave.tsx, src/components/Landing/Bounties.tsx, src/components/Landing/Builders.tsx, src/components/Landing/DeveloperCommunity.tsx
This PR adds fixes & improvements to landing page.
=> fix: Landing page issues & improvements

src/components/Landing/Bounties.tsx, src/components/Landing/Header.tsx, src/components/Landing/InteractiveRepo/BranchButton.tsx, src/components/Landing/Navbar.tsx, src/components/Navbar/UserProfileButton.tsx, src/helpers/hooks/useAuth.ts
This PR adds fix for layout zoom issue on mobile when user is on landing page
This also adds docs link to CTA on landing page
=> fix: landing page layout issues on mobile

src/pages/home/Home.tsx
This PR updates on click action of import repo to point to docs for that feature.
=> refactor: update import repo button to redirect to docs

index.html, package.json, src/components/DragonDeploy/ArNSSetupModal.tsx, src/components/DragonDeploy/DragonDeploy.tsx, src/helpers/wallet/getPublicKey.ts, src/helpers/wallet/getSigner.ts, src/helpers/wallet/signAndSend.ts, src/lib/dragondeploy/arns.ts, src/lib/dragondeploy/index.ts, src/lib/git/pull-request.ts, src/lib/git/repo.ts, src/lib/user.ts, src/main.tsx, src/pages/home/components/NewRepoModal.tsx, src/pages/home/hooks/useFetchUserRepos.ts, src/pages/pull/read/index.tsx, src/stores/issues/actions/index.ts, src/stores/repository-core/actions/git.ts, src/stores/repository-core/actions/repoMeta.ts, src/stores/repository-core/index.ts, src/stores/user/actions/index.ts, vite.config.ts, yarn.lock
This PR adds othent as strategy and updates all necessary places to get signer and submit tx conditionally based on active strategy.
This PR temporarily disables creation of private repos using othent accounts.
=> feat: add othent strategy

src/pages/home/components/Sidebar.tsx, src/pages/repository/components/RepoHeader.tsx
This PR adds improvements to home page sidebar:
- Replace address with username if available
- Add a search input to search repos
=> feat: Sidebar improvements

scripts/deploy.js, src/helpers/constants.ts, src/pages/profile/components/tabs/repositories/components/RepoItem.tsx, src/pages/profile/components/tabs/repositories/index.tsx, src/stores/user/actions/index.ts, src/types/repository.ts, warp/protocol-land/actions/repository.ts, warp/protocol-land/types/index.ts
This PR adds the following enhancements to User profile repositories tab:
- Show "forked from (owner/username)/repoName"
- Add repository search input
- Show Public/Private label
=> feat: User profile repositories tab enhancements

src/pages/home/components/Activities.tsx
We currently fetch interactions validity from DRE node but DRE node seems to be out of sync for Protocol Land. So, instead of fetching it from DRE node we could use the local state validity to check if the interaction is valid or not to show on the explore page.
=> fix: Load state & validity from local state

src/helpers/getWrapContract.ts, src/lib/git/pull-request.ts, src/lib/git/repo.ts, src/pages/home/hooks/useFetchUserRepos.ts, src/stores/issues/actions/index.ts, src/stores/repository-core/actions/repoMeta.ts, src/stores/user/actions/index.ts
This PR improves contract loading by using a remote cache URL to sync state for the first time.
=> feat: Improve contract loading

src/pages/issue/read/tabs/bounty/ReadBountyModal.tsx
This PR makes sure to check payment tx when someone is closing the bounty. 
It checks if a payment tx is valid and then if the amount sent in the tx matches the bounty amount.
=> feat: add payment tx verification logic to bounties

src/helpers/constants.ts, src/pages/issue/read/tabs/bounty/BountyRow.tsx, src/pages/issue/read/tabs/bounty/NewBountyModal.tsx, src/pages/issue/read/tabs/bounty/ReadBountyModal.tsx, src/pages/issue/read/tabs/bounty/index.tsx, src/pages/repository/components/RepoHeader.tsx, src/stores/issues/actions/index.ts, src/stores/issues/index.ts, src/stores/issues/types.ts, src/types/repository.ts, warp/protocol-land/actions/issues.ts, warp/protocol-land/types/index.ts
This PR allows bounties to be created with base(USD/AR).
Heres an example:
- If i create a bounty with USD as base and i enter 100 as amount, then AR worth of 100USD will be calculated and showed.
- if i create a bounty with AR as base and i enter 5 AR as amount, then USD worth of 5 AR will be calculated and showed.
=> feat: add amount base change to bounty

src/lib/git/helpers/oid.ts
This PR changes readFilesFromCommit function to work iteratively. This is to prevent Max call stack size exceeded error.
=> fix: do readFilesFromCommit iteratively

src/pages/hackathon/CreateHackathon.tsx, src/pages/hackathon/Hackathon.tsx, src/pages/hackathon/components/steps/participate/TeamSelectCreateStep.tsx, src/pages/hackathon/utils/prepareHackathonItemToPost.ts, src/stores/hackathon/actions/index.ts
Add hackathon create bug fixes
=> fix: create hackathon bug fixes

src/pages/hackathon/SubmissionDetails.tsx, src/pages/hackathon/SubmitHackathon.tsx, src/pages/hackathon/components/tabs/submissions/SubmissionsTab.tsx, src/pages/hackathon/utils/getLogoUrl.ts
=> fix: properly show submission logo images and md description

src/helpers/aoconnect/index.ts, src/lib/bonding-curve/index.ts, src/lib/decentralize/index.ts, src/lib/git/repo.ts
=> release: gateway and subsidization change
